name: localhost
brand:
  text: /statics/sites/localhost/images/branding.svg
  symbol: /statics/sites/localhost/images/logo.svg
favicon: /statics/sites/localhost/images/mimiza.svg
env: development
locale: en
fiat: USD